# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(276, 279)
        self.lbLogin = QtWidgets.QLabel(Dialog)
        self.lbLogin.setGeometry(QtCore.QRect(20, 90, 35, 35))
        self.lbLogin.setStyleSheet("image: url(:/img/user.png);")
        self.lbLogin.setText("")
        self.lbLogin.setObjectName("lbLogin")
        self.lbPassword = QtWidgets.QLabel(Dialog)
        self.lbPassword.setGeometry(QtCore.QRect(20, 140, 35, 35))
        self.lbPassword.setStyleSheet("image: url(:/img/password.png);")
        self.lbPassword.setObjectName("lbPassword")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(60, 89, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 142, 171, 31))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.btnLogin = QtWidgets.QPushButton(Dialog)
        self.btnLogin.setGeometry(QtCore.QRect(60, 200, 81, 31))
        self.btnLogin.setObjectName("btnLogin")
        self.btnLogin_2 = QtWidgets.QPushButton(Dialog)
        self.btnLogin_2.setGeometry(QtCore.QRect(150, 200, 81, 31))
        self.btnLogin_2.setObjectName("btnLogin_2")
        self.lbLogo = QtWidgets.QLabel(Dialog)
        self.lbLogo.setGeometry(QtCore.QRect(30, 30, 221, 41))
        self.lbLogo.setStyleSheet("image: url(:/img/EF_English_Live_logo.png);")
        self.lbLogo.setObjectName("lbLogo")
        self.lbPassword_2 = QtWidgets.QLabel(Dialog)
        self.lbPassword_2.setGeometry(QtCore.QRect(80, 240, 111, 21))
        self.lbPassword_2.setObjectName("lbPassword_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbPassword.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "username"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "password"))
        self.btnLogin.setText(_translate("Dialog", "Sign in"))
        self.btnLogin_2.setText(_translate("Dialog", "Exit"))
        self.lbLogo.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.lbPassword_2.setText(_translate("Dialog", "<html><head/><body><p>www.englishlive.com</p></body></html>"))

    def get_credentials(self):
        # Obtém as credenciais de login
        self.email_usuario = self.lineEdit.text()
        self.senha_usuario = self.lineEdit_2.text()
        self.Dialog.accept()  # Fecha o diálogo

    def show_login(self):
        # Exibe a janela de login e captura as credenciais
        self.Dialog = QtWidgets.QDialog()
        self.setupUi(self.Dialog)
        self.btnLogin.clicked.connect(self.get_credentials)  # Chama o método para capturar credenciais
        # Conecta o botão "Exit" (btnLogin_2) ao método de fechamento da aplicação
        self.btnLogin_2.clicked.connect(self.close_application)  # Aqui estamos chamando a função para fechar a aplicação
        self.Dialog.exec_()  # Aguarda até o diálogo ser fechado
        return self.email_usuario, self.senha_usuario
    
    def close_application(self):
        print("Fechando a aplicação...")  # Para verificar se o método está sendo chamado
        self.Dialog.close()  # Fecha o diálogo
        sys.exit()  # Encerra a aplicação de forma robusta

import image


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
